# Generated by Django 4.1.1 on 2023-02-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_product_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
